
single: single.c
	gcc -Wall -fopenmp single.c -lm -o single
	
1: 1\ critical\ section.c
	gcc -Wall -fopenmp 1\ critical\ section.c -lm -o 1\ critical\ section
	
2: 2\ atomic.c
	gcc -Wall -fopenmp 2\ atomic.c -lm -o 2\ atomic
	
3: 3\ n-locks.c
	gcc -Wall -fopenmp 3\ n-locks.c -lm -o 3\ n-locks
	
4: 4\ extra\ calculations.c
	gcc -Wall -fopenmp 4\ extra\ calculations.c -lm -o 4\ extra\ calculations
	
5: 5\ local\ vector.c
	gcc -Wall -fopenmp 5\ local\ vector.c -lm -o 5\ local\ vector
